name: flutter_kernel_transformers
version: 0.0.1-dev
description: Kernel transformers that operate on Flutter source code.
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

dependencies:
  kernel: any
  meta: any

dev_dependencies:
  test: any
  when: any
